import Head from "next/head";
import Link from "next/link";

// import Image from "next/image";

// import requests from "../utils/requests";

export default function Home({ results }) {
  console.log("results", results);
  return (
    <div>
      <Head>
        <title>MovieSite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        <li>
          <Link href="/register">
            <a>Registeration</a>
          </Link>
        </li>

        <li>
          <Link href="/book">
            <a>Booking</a>
          </Link>
        </li>

        <li>
          <Link href="/slip">
            <a>Upload Slip</a>
          </Link>
        </li>
      </ul>
    </div>
  );
}

export async function getServerSideProps(context) {
  // const genre = context.query.genre;

  return {
    props: {},
  };
}
